#!/bin/bash

X=0

echo "Give me a number"
read NUM
echo "Cool, I can count to $NUM, check it out"

while [ $NUM -gt $X ]
do
    let  X=X+1       # use let for making the expression numerical othrwise it will store string 
    echo $X
done